<?php
/**
 * This file was automatically generated by autoload_generator.php
 *
 * Do not edit this file directly
 */

spl_autoload_register(function($className) {
    static $classMap;
    if (!isset($classMap)) {
        $classMap = [
            'libdns\datatypes\anything'              => __DIR__ . '/../src/LibDNS/DataTypes/Anything.php',
            'libdns\datatypes\bitmap'                => __DIR__ . '/../src/LibDNS/DataTypes/BitMap.php',
            'libdns\datatypes\char'                  => __DIR__ . '/../src/LibDNS/DataTypes/Char.php',
            'libdns\datatypes\characterstring'       => __DIR__ . '/../src/LibDNS/DataTypes/CharacterString.php',
            'libdns\datatypes\complextype'           => __DIR__ . '/../src/LibDNS/DataTypes/ComplexType.php',
            'libdns\datatypes\datatype'              => __DIR__ . '/../src/LibDNS/DataTypes/DataType.php',
            'libdns\datatypes\datatypebuilder'       => __DIR__ . '/../src/LibDNS/DataTypes/DataTypeBuilder.php',
            'libdns\datatypes\datatypedefinitions'   => __DIR__ . '/../src/LibDNS/DataTypes/DataTypeDefinitions.php',
            'libdns\datatypes\datatypefactory'       => __DIR__ . '/../src/LibDNS/DataTypes/DataTypeFactory.php',
            'libdns\datatypes\domainname'            => __DIR__ . '/../src/LibDNS/DataTypes/DomainName.php',
            'libdns\datatypes\ipv4address'           => __DIR__ . '/../src/LibDNS/DataTypes/IPv4Address.php',
            'libdns\datatypes\ipv6address'           => __DIR__ . '/../src/LibDNS/DataTypes/IPv6Address.php',
            'libdns\datatypes\long'                  => __DIR__ . '/../src/LibDNS/DataTypes/Long.php',
            'libdns\datatypes\short'                 => __DIR__ . '/../src/LibDNS/DataTypes/Short.php',
            'libdns\datatypes\simpletype'            => __DIR__ . '/../src/LibDNS/DataTypes/SimpleType.php',
            'libdns\datatypes\simpletypes'           => __DIR__ . '/../src/LibDNS/DataTypes/SimpleTypes.php',
            'libdns\decoder\decoder'                 => __DIR__ . '/../src/LibDNS/Decoder/Decoder.php',
            'libdns\decoder\decoderfactory'          => __DIR__ . '/../src/LibDNS/Decoder/DecoderFactory.php',
            'libdns\decoder\decodingcontext'         => __DIR__ . '/../src/LibDNS/Decoder/DecodingContext.php',
            'libdns\decoder\decodingcontextfactory'  => __DIR__ . '/../src/LibDNS/Decoder/DecodingContextFactory.php',
            'libdns\encoder\encoder'                 => __DIR__ . '/../src/LibDNS/Encoder/Encoder.php',
            'libdns\encoder\encoderfactory'          => __DIR__ . '/../src/LibDNS/Encoder/EncoderFactory.php',
            'libdns\encoder\encodingcontext'         => __DIR__ . '/../src/LibDNS/Encoder/EncodingContext.php',
            'libdns\encoder\encodingcontextfactory'  => __DIR__ . '/../src/LibDNS/Encoder/EncodingContextFactory.php',
            'libdns\enumeration'                     => __DIR__ . '/../src/LibDNS/Enumeration.php',
            'libdns\messages\message'                => __DIR__ . '/../src/LibDNS/Messages/Message.php',
            'libdns\messages\messagefactory'         => __DIR__ . '/../src/LibDNS/Messages/MessageFactory.php',
            'libdns\messages\messageopcodes'         => __DIR__ . '/../src/LibDNS/Messages/MessageOpCodes.php',
            'libdns\messages\messageresponsecodes'   => __DIR__ . '/../src/LibDNS/Messages/MessageResponseCodes.php',
            'libdns\messages\messagetypes'           => __DIR__ . '/../src/LibDNS/Messages/MessageTypes.php',
            'libdns\packets\labelregistry'           => __DIR__ . '/../src/LibDNS/Packets/LabelRegistry.php',
            'libdns\packets\packet'                  => __DIR__ . '/../src/LibDNS/Packets/Packet.php',
            'libdns\packets\packetfactory'           => __DIR__ . '/../src/LibDNS/Packets/PacketFactory.php',
            'libdns\records\question'                => __DIR__ . '/../src/LibDNS/Records/Question.php',
            'libdns\records\questionfactory'         => __DIR__ . '/../src/LibDNS/Records/QuestionFactory.php',
            'libdns\records\record'                  => __DIR__ . '/../src/LibDNS/Records/Record.php',
            'libdns\records\recordcollection'        => __DIR__ . '/../src/LibDNS/Records/RecordCollection.php',
            'libdns\records\recordcollectionfactory' => __DIR__ . '/../src/LibDNS/Records/RecordCollectionFactory.php',
            'libdns\records\recordtypes'             => __DIR__ . '/../src/LibDNS/Records/RecordTypes.php',
            'libdns\records\resource'                => __DIR__ . '/../src/LibDNS/Records/Resource.php',
            'libdns\records\resourcebuilder'         => __DIR__ . '/../src/LibDNS/Records/ResourceBuilder.php',
            'libdns\records\resourceclasses'         => __DIR__ . '/../src/LibDNS/Records/ResourceClasses.php',
            'libdns\records\resourcefactory'         => __DIR__ . '/../src/LibDNS/Records/ResourceFactory.php',
            'libdns\records\resourceqclasses'        => __DIR__ . '/../src/LibDNS/Records/ResourceQClasses.php',
            'libdns\records\resourceqtypes'          => __DIR__ . '/../src/LibDNS/Records/ResourceQTypes.php',
            'libdns\records\resourcetypes'           => __DIR__ . '/../src/LibDNS/Records/ResourceTypes.php',
        ];
    }

    $className = strtolower($className);
    if (isset($classMap[$className])) {
        require $classMap[$className];
    }
});
